<?php
/**
 * @var $block \Zhixing\UnionPayInstallmentsQrcode\Block\WaitingConfirm
 */
?>

<style>
    *{
        border: 0 none;
        font-family: inherit;
        font-feature-settings: inherit;
        font-kerning: inherit;
        font-language-override: inherit;
        font-size: 100%;
        font-size-adjust: inherit;
        font-stretch: inherit;
        font-style: inherit;
        font-synthesis: inherit;
        font-variant: inherit;
        font-weight: inherit;
        line-height: inherit;
        margin: 0;
        padding: 0;
        vertical-align: baseline;
        outline: none;
    }
    @keyframes rotating {
        0% {
            transform: rotate(0deg);
        }
        100% {
            transform: rotate(360deg);
        }
    }

    .spinner {
        width: 60px;
        height: 60px;
        animation: rotating 1s linear infinite;
    }
    .loader-container {
        background: rgba(0, 0, 0, 0.5);
        width: 100%;
        height: 100vh;
        padding-top: 140px;
        box-sizing: border-box;
        text-align: center;
    }

    .loader-container .loader {
        width: 100%;
        height: 200px;
        background: #fff;
        margin: 0 auto;
        font-size: 18px;
    }

    .loader-container .loader .txt {
        line-height: 200px;
        width: 100%;
    }

    .loader-container .close-x {
        width: 30px;
        height: 30px;
        display: inline-block;
        margin: 5px auto 0;
        position: relative;
    }

    .loader-container .close-x::after {
        position: absolute;
        content: '';
        width: 1px;
        height: 30px;
        top: 7px;
        left: 16px;
        background: #fff;
        transform: rotate(45deg);
    }

    .loader-container .close-x::before {
        position: absolute;
        background: #fff;
        content: '';
        width: 1px;
        height: 30px;
        top: 7px;
        left: 16px;
        transform: rotate(-45deg);
    }
</style>
<div class="loader-container">
    <div class="loader">
        <img class="spinner" src="<?= (string) $block->getViewFileUrl('images/preloader.svg') ?>" alt="preloader">
        <div class="txt"><?= (string) __('Confirming...');?></div>
    </div>
    <a class="close-x" href="<?= (string) $block->getContinueShoppingUrl();?>"></a>
</div>

<script>
    require.config({
        deps: [
            'jquery'
        ],
        callback: function ($) {
            isOk = false;
            (function poll() {
                setTimeout(function() {
                    if(isOk)
                        return;
                    $.ajax(
                        {   url: "<?= (string) $block->getPaidUrl();?>",
                            data: {orderId:"<?= (string) $block->getRealOrderId();?>"},
                            success: function(data) {
                                if ($.trim(data) === 'ok') {
                                    $(window.location).attr('href', '<?= (string) $block->getSuccessUrl();?>');
                                    isOk = true;
                                }
                            },
                            complete: poll
                        });
                }, 5000);
            })()
        }
    });
</script>