<?php
/**
 * @var $block \Zhixing\UnionPayInstallmentsQrcode\Block\Form
 */
$instructions = $block->getInstructions();
?>
<?php if ($instructions) : ?>
    <?php $methodCode = $block->escapeHtml($block->getMethodCode());?>
    <div class="items <?= (string) $methodCode ?> instructions agreement checkout-agreement-item-content"
         id="payment_form_<?= (string) $methodCode ?>" style="display: none;">
        <?= (string) nl2br($block->escapeHtml($instructions)) ?>
    </div>
<?php endif; ?>

