<?php
/**
 * @var $block \Zhixing\UnionPayInstallmentsQrcode\Block\Redirect
 */
?>
<style>
    body{
        background-color:#fff;
    }
    .uiq-container {
        font-size: 14px;
        margin:0 auto;
        width: 100%;
    }
    .uiq-container p {
        border: 1px solid #efefef;
        width: 50%;
        vertical-align: middle;
        padding: 15px;
        text-align: center;
        margin:0 auto;
        margin-top: 45px;
    }
    .uiq-container img {
        vertical-align: middle;
    }
</style>
<div class="uiq-container">
    <?php if ($block->canContinuePay()) :?>
        <?php if (!empty($qrcode = $block->getQrcode())) :?>
            <img src="<?= (string) $qrcode; ?>" alt="" />
        <?php else : ?>
            <p><?= (string) __('Sorry, get qrcode failed, please retry later.'); ?></p>
        <?php endif;?>
    <?php else : ?>
        <p><?= (string) __('Sorry, the order exceeds payment time, please re-order it.'); ?></p>
    <?php endif;?>
</div>
